<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diff_drive_description" params="prefix">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_width" value="0.115"/>
    <xacro:property name="wheel_separation_front_center" value="0.969"/>
    <xacro:property name="wheel_separation_rear" value="0.877"/>
    <xacro:property name="base_length" value="1.0813779"/>
    <xacro:property name="base_width" value="0.902084416"/>
    <xacro:property name="base_height" value="0.26082"/>

    <!-- Wheel positions (X = front/back, Y = left/right) -->
    <xacro:property name="front_x" value="0.35"/>
    <xacro:property name="center_x" value="0.0"/>
    <xacro:property name="rear_x" value="-0.35"/>

    <!-- Mass properties (arbitrary values for simulation) -->
    <xacro:property name="base_mass" value="50.0"/>
    <xacro:property name="wheel_mass" value="2.0"/>

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
          ixx="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
          iyy="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" iyz="0.0"
          izz="${base_mass / 12.0 * (base_length*base_length + base_width*base_width)}"/>
      </inertial>
    </link>

    <!-- Wheel macro for reuse -->
    <xacro:macro name="wheel_link" params="name">
      <link name="${prefix}${name}_wheel_link">
        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
          <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          </geometry>
          <material name="black">
            <color rgba="0.1 0.1 0.1 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
          <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" ixy="0.0" ixz="0.0"
            iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" iyz="0.0"
            izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>
    </xacro:macro>

    <!-- Create all wheel links -->
    <xacro:wheel_link name="front_left"/>
    <xacro:wheel_link name="front_right"/>
    <xacro:wheel_link name="center_left"/>
    <xacro:wheel_link name="center_right"/>
    <xacro:wheel_link name="rear_left"/>
    <xacro:wheel_link name="rear_right"/>

    <!-- Front wheels -->
    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_left_wheel_link"/>
      <origin xyz="${front_x} ${wheel_separation_front_center/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_right_wheel_link"/>
      <origin xyz="${front_x} ${-wheel_separation_front_center/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- Center wheels (inverted axis to match motor direction) -->
    <joint name="${prefix}center_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}center_left_wheel_link"/>
      <origin xyz="${center_x} ${wheel_separation_front_center/2} 0" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <joint name="${prefix}center_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}center_right_wheel_link"/>
      <origin xyz="${center_x} ${-wheel_separation_front_center/2} 0" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- Rear wheels -->
    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_left_wheel_link"/>
      <origin xyz="${rear_x} ${wheel_separation_rear/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_right_wheel_link"/>
      <origin xyz="${rear_x} ${-wheel_separation_rear/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
    </joint>

  </xacro:macro>

</robot>
